apiVersion: batch/v1
kind: Job
metadata:
  name: fastapi-migration
spec:
  ttlSecondsAfterFinished: 100 # Удалить этот под через 100 сек после завершения
  template:
    spec:
      containers:
        - name: alembic
          image: technobladedocker/fastapi-todo:v1
          imagePullPolicy: Always
          # Главная команда для запуска миграйи alembic
          command: ["alembic", "upgrade", "head"]

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
      restartPolicy: Never
